'use client';
/**
 * Day 0 — "Before You Start" orientation.
 * Renders books.sprint_intro markdown (already generated by day_0_generator).
 * Optional: capture "your situation this week" so Day 1+ return-loop has a spine.
 */
import React, { useState } from 'react';
import Link from 'next/link';

/**
 * Minimal markdown → React for Day 0 format:
 *   # title
 *   paragraphs
 *   ## Section
 *   **Bold teaching title** + body
 *   trailing Day 1 handoff question
 */
function renderIntro(md) {
  if (!md || !String(md).trim()) return null;

  const lines = String(md).replace(/\r\n/g, '\n').split('\n');
  const blocks = [];
  let i = 0;
  let key = 0;

  const flushParagraph = (buf) => {
    const text = buf.join(' ').trim();
    if (!text) return;
    // Inline **bold**
    const parts = [];
    const re = /\*\*([^*]+)\*\*/g;
    let last = 0;
    let m;
    let pkey = 0;
    while ((m = re.exec(text)) !== null) {
      if (m.index > last) parts.push(text.slice(last, m.index));
      parts.push(
        <strong key={`b${pkey++}`} style={{ color: 'var(--text-main)', fontWeight: 700 }}>
          {m[1]}
        </strong>
      );
      last = m.index + m[0].length;
    }
    if (last < text.length) parts.push(text.slice(last));
    blocks.push(
      <p
        key={`p${key++}`}
        style={{
          fontSize: '1.02rem',
          lineHeight: 1.7,
          color: 'var(--text-main)',
          margin: '0 0 1.1rem 0',
        }}
      >
        {parts.length ? parts : text}
      </p>
    );
  };

  while (i < lines.length) {
    const line = lines[i];
    const trimmed = line.trim();

    if (!trimmed) {
      i += 1;
      continue;
    }

    // # Title
    if (trimmed.startsWith('# ') && !trimmed.startsWith('## ')) {
      blocks.push(
        <h1
          key={`h1${key++}`}
          className="text-gradient"
          style={{
            fontSize: '2rem',
            fontWeight: 800,
            letterSpacing: '-0.02em',
            marginBottom: 8,
            marginTop: key === 0 ? 0 : 28,
          }}
        >
          {trimmed.slice(2).trim()}
        </h1>
      );
      i += 1;
      continue;
    }

    // ## Section
    if (trimmed.startsWith('## ')) {
      blocks.push(
        <h2
          key={`h2${key++}`}
          style={{
            fontFamily: "'DM Mono', monospace",
            fontSize: '0.72rem',
            fontWeight: 700,
            textTransform: 'uppercase',
            letterSpacing: '0.1em',
            color: 'var(--brand-teal)',
            margin: '2rem 0 0.85rem 0',
          }}
        >
          {trimmed.slice(3).trim()}
        </h2>
      );
      i += 1;
      continue;
    }

    // Teaching card: **Name** then body lines until blank or next header
    const boldOnly = trimmed.match(/^\*\*([^*]+)\*\*\s*$/);
    if (boldOnly) {
      const title = boldOnly[1];
      i += 1;
      const bodyBuf = [];
      while (i < lines.length) {
        const t = lines[i].trim();
        if (!t) break;
        if (t.startsWith('#') || t.match(/^\*\*[^*]+\*\*\s*$/)) break;
        bodyBuf.push(t);
        i += 1;
      }
      blocks.push(
        <div
          key={`t${key++}`}
          className="glass-panel"
          style={{
            marginBottom: 12,
            padding: '16px 18px',
            background: 'rgba(25,190,227,0.03)',
          }}
        >
          <div
            style={{
              fontWeight: 700,
              fontSize: '1rem',
              color: 'var(--text-main)',
              marginBottom: 8,
              lineHeight: 1.4,
            }}
          >
            {title}
          </div>
          {bodyBuf.length > 0 && (
            <p
              style={{
                margin: 0,
                fontSize: '0.95rem',
                lineHeight: 1.65,
                color: 'rgba(238,242,247,0.82)',
              }}
            >
              {bodyBuf.join(' ')}
            </p>
          )}
        </div>
      );
      continue;
    }

    // Normal paragraph (accumulate until blank)
    const buf = [trimmed];
    i += 1;
    while (i < lines.length) {
      const t = lines[i].trim();
      if (!t) break;
      if (t.startsWith('#') || t.match(/^\*\*[^*]+\*\*\s*$/)) break;
      // line that is only **x** body on same line already handled
      if (t.startsWith('**') && t.endsWith('**') && t.indexOf('**', 2) === t.length - 2) break;
      buf.push(t);
      i += 1;
    }
    flushParagraph(buf);
  }

  return blocks;
}

export default function Day0View({
  book,
  introMarkdown,
  bookId,
  situationText,
  onSituationChange,
  onSituationBlur,
  showSituation = true,
}) {
  const [localSituation, setLocalSituation] = useState(situationText || '');

  // Keep in sync if parent hydrates after mount
  React.useEffect(() => {
    setLocalSituation(situationText || '');
  }, [situationText]);

  const rendered = renderIntro(introMarkdown);

  return (
    <>
      <div className="ambient-glow" />
      <nav className="glass-nav">
        <div className="nav-content">
          <Link href="/library" className="logo">
            <img src="/SummitSkills-Logo.png" alt="SummitSkills" className="logo-img" />
            Summit<span>Skills</span>
          </Link>
          <div className="nav-actions">
            <Link href="/library" className="btn-outline small">Exit to Library</Link>
          </div>
        </div>
      </nav>

      <main
        className="container day-main"
        style={{ maxWidth: 768, paddingTop: 40, paddingBottom: 100 }}
      >
        {/* Header chrome */}
        <div style={{ marginBottom: 32 }}>
          <div className="tag-featured" style={{ marginBottom: 14 }}>
            <div className="pulse-dot" />
            <span style={{ fontFamily: "'DM Mono', monospace" }}>Day 0</span>
            <span style={{ color: 'rgba(25,190,227,0.5)' }}>/</span>
            <span style={{ fontFamily: "'DM Mono', monospace" }}>7</span>
            <span style={{ color: 'rgba(25,190,227,0.5)', margin: '0 4px' }}>·</span>
            <span style={{ fontFamily: 'var(--font-sans)' }}>Before you start</span>
          </div>
          <p
            style={{
              fontFamily: "'DM Mono', monospace",
              fontSize: '0.7rem',
              fontWeight: 700,
              textTransform: 'uppercase',
              letterSpacing: '0.1em',
              color: 'var(--brand-teal)',
              margin: 0,
            }}
          >
            {book?.sprint_title || book?.title}
          </p>
        </div>

        {/* Intro body */}
        <div style={{ marginBottom: 28, textAlign: 'left' }}>
          {rendered}
        </div>

        {/* Situation capture — same field Days 1–7 echo */}
        {showSituation && (
          <div
            className="glass-panel"
            style={{
              marginBottom: 28,
              padding: '18px 20px',
              borderColor: 'rgba(25,190,227,0.3)',
              background: 'rgba(25,190,227,0.05)',
            }}
          >
            <div className="tag-featured" style={{ marginBottom: 10 }}>
              Hold this all week
            </div>
            <p
              style={{
                fontSize: '0.88rem',
                lineHeight: 1.5,
                color: 'rgba(238,242,247,0.55)',
                margin: '0 0 12px 0',
              }}
            >
              Name one person, habit, or thread you will practice on. Every day will come
              back to this — so the sprint is about your work, not generic tips.
            </p>
            <textarea
              className="journal-input"
              value={localSituation}
              onChange={(e) => {
                setLocalSituation(e.target.value);
                onSituationChange?.(e.target.value);
              }}
              onBlur={() => onSituationBlur?.(localSituation)}
              placeholder="e.g. Status updates from Jordan that never land before standup"
              rows={2}
              style={{ minHeight: 64, marginBottom: 0 }}
            />
          </div>
        )}

        {/* CTA into Day 1 */}
        <div
          className="glass-panel mission-panel highlighted"
          style={{ marginBottom: 24, textAlign: 'center', padding: '24px 20px' }}
        >
          <p
            style={{
              fontSize: '0.95rem',
              color: 'rgba(238,242,247,0.65)',
              margin: '0 0 18px 0',
              lineHeight: 1.5,
            }}
          >
            Fifteen minutes a day. One move. Real work.
          </p>
          <Link
            href={`/summit/${bookId}/day/1`}
            className="btn-primary-large"
            style={{ display: 'inline-flex', textDecoration: 'none' }}
          >
            Start Day 1
            <span className="arrow" style={{ fontSize: '1.1em' }}>→</span>
          </Link>
        </div>

        <div style={{ textAlign: 'center' }}>
          <Link
            href="/library"
            style={{
              fontSize: '0.8rem',
              color: 'rgba(255,255,255,0.35)',
              textDecoration: 'none',
            }}
          >
            ← Back to library
          </Link>
        </div>
      </main>
    </>
  );
}
